#!/bin/bash
#PBS -N 2_pca_gpu_test
#PBS -l select=1:ncpus=8:ngpus=1:mem=16gb
#PBS -l walltime=01:00:00
#PBS -o logs/2_pca_gpu_test.out
#PBS -e logs/2_pca_gpu_test.err

# Move to the directory from which job submitted
cd $PBS_O_WORKDIR

echo "$(date "+%Y-%m-%d %H:%M:%S") - 2_pca_gpu_test started" >> $HOME/times.log
nvidia-smi --query-gpu=name --format=csv,noheader

# Paths
CONTAINER_PATH="$PBS_O_WORKDIR/containers/mechinterp_cont.sif"
SCRIPT_PATH="$PBS_O_WORKDIR/scripts/analyses/2_pca_gpu_test.py"

# Run the script inside the container
singularity exec --nv \
    -B "$HOME/mech-typo-detect:/workspace" \
    "$CONTAINER_PATH" \
    python "$SCRIPT_PATH" --tensor-parallel

echo "$(date "+%Y-%m-%d %H:%M:%S") - 2_pca_gpu_test finished" >> $HOME/times.log
