#!/bin/bash
#PBS -N min_test2
#PBS -l select=1:ncpus=8:mem=32gb
#PBS -l walltime=16:00:00
#PBS -o logs/min_test2.out
#PBS -e logs/min_test2.err

# Move to the directory from which job submitted
cd $PBS_O_WORKDIR

echo "$(date "+%Y-%m-%d %H:%M:%S") - min_test2 started" >> $HOME/times.log
nvidia-smi --query-gpu=name --format=csv,noheader

# Paths
CONTAINER_PATH="$PBS_O_WORKDIR/containers/mechinterp_cont.sif"
SCRIPT_PATH="$PBS_O_WORKDIR/scripts/inference/min_test2.py"

# Run the script inside the container
singularity exec --nv \
    -B "$HOME/activation_training:/workspace" \
    "$CONTAINER_PATH" \
    python "$SCRIPT_PATH" --tensor-parallel

echo "$(date "+%Y-%m-%d %H:%M:%S") - min_test2 finished" >> $HOME/times.log
